### ISSUE TITLE
kafka ui does not run on local setup

### ISSUE THREAD

**Issue by BRO3886** [flexprice/flexprice#67]
Was following setup.md

```bash
make setup-local
```

On running this command, everything else runs flawlessly except kafka ui, which did not run. The container was not even created. On checking the `docker-compose.yml` I saw that the config mentions a profile

```
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:main
    profiles:
      - dev
  ...
```

`make setup-local` runs `docker compose up -d --build`, but profile is not mentioned here. Either profile should be mentioned in docker compose up or removed from the compose file
